sudo: required
services: 
  - docker

before_install:
  - docker build -t jjneojiajun/react-nginx-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true jjneojiajun/react-nginx-docker npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-nginx-docker"
  env: "ReactNginxDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-511788195710"
  bucket_path: "react-nginx-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  