sudo: required
services: 
  - docker

before_install:
  - docker build -t jjneojiajun/react-nginx-docker -f Dockerfile.dev .

script:
  - docker run jjneojiajun/react-nginx-docker npm run test -- --coverage
  